export const nationality = [
  'AFRICA',
  'ANTIGUE & BARBUDA',
  'AUSTRALIA',
  'AUSTRIA',
  'BANGLADESH',
  'BELGIUM',
  'BRUNEI',
  'CANADA',
  'CYPRUS',
  'DENMARK',
  'FRANCE',
  'GERMANY',
  'GREAT BRITAIN',
  'GUERNSEY (CHANNEL ISLANDS)',
  'HONDURAS',
  'HONG KONG',
  'INDIA',
  'INDONESIA',
  'IRELAND',
  'ISLE OF MAN',
  'ISRAEL',
  'ITALY',
  'JAPAN',
  'JERSEY (CHANNEL ISLANDS)',
  'JORDAN',
  'KINGDOM OF CAMBODIA',
  'KOREA',
  'LIBERIA',
  'LUXEMBOURG',
  'MALAYSIA',
  'MALTA',
  'MAURITIUS',
  'MYANMAR',
  'NEPAL',
  'NETHERLANDS',
  'NEW ZEALAND',
  'NORWAY',
  'PAKISTAN',
  'PANAMA',
  'PHILIPPINE',
  'POLAND',
  'PORTUGAL',
  'REPUBLIC OF CHINA',
  'SINGAPORE',
  'SPAIN',
  'SRI LANKA',
  'SWEDEN',
  'SWITZERLAND',
  'TAIWAN',
  'THAILAND',
  'TURKEY',
  'UNITED STATES',
  'VIETNAM'
]

export const formatter = new Intl.NumberFormat('ms', {
  style: 'decimal',
  currency: 'MYR',
});